import { useMemo } from 'react';
import { Link } from 'react-router-dom';
import { Users, Calendar, Heart, ArrowRight, Quote, GitFork, FileText, Bell } from 'lucide-react';
import { motion } from 'framer-motion';
import { CURRENT_USER } from '../data/mockData';
import { useFamily } from '../context/FamilyContext';

export default function DashboardPage() {
  const { members, familyGroups, events, activities } = useFamily();
  const stats = [
    { label: 'Family Members', value: members.length, icon: Users, color: 'bg-orange-500', trend: 'View all members', to: '/profiles' },
    { label: 'Family Branches', value: familyGroups.length, icon: GitFork, color: 'bg-blue-500', trend: 'Explore branches', to: '/family-history' },
    { label: 'Family Events', value: events.length, icon: Calendar, color: 'bg-green-500', trend: 'View calendar', to: '/events' },
    { label: 'Memorials', value: members.filter((member) => member.status === 'Deceased').length, icon: Heart, color: 'bg-red-500', trend: 'Remember family', to: '/memorial' }
  ];
  const recentActivities = useMemo(() => activities.slice(0, 5), [activities]);

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <header><h1 className="flex items-center gap-2 text-3xl font-bold text-slate-900 dark:text-white">Welcome back, {CURRENT_USER.name.split(' ')[0]} 👋</h1><p className="mt-1 text-slate-500 dark:text-slate-400">Here’s what’s happening in your family archive.</p></header>
      <section aria-label="Family archive summary" className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat, index) => <motion.article key={stat.label} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }} className="rounded-3xl border border-slate-100 bg-white p-5 shadow-premium dark:border-slate-800 dark:bg-[#111D29]"><span className={`flex h-11 w-11 items-center justify-center rounded-2xl ${stat.color} text-white`}><stat.icon size={21} /></span><p className="mt-4 text-xs font-semibold text-slate-500">{stat.label}</p><p className="mt-1 text-3xl font-black text-slate-900 dark:text-white">{stat.value}</p><Link to={stat.to} className="mt-2 inline-flex items-center gap-1 text-[10px] font-black uppercase tracking-wider text-primary hover:underline">{stat.trend}<ArrowRight size={12} /></Link></motion.article>)}</section>
      <div className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]">
        <section className="overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-premium dark:border-slate-800 dark:bg-[#111D29]"><header className="flex items-center justify-between border-b border-slate-100 p-5 dark:border-slate-800"><div><h2 className="text-sm font-black text-slate-900 dark:text-white">Family tree</h2><p className="mt-1 text-[10px] text-slate-400">{members.length} profiles preserved</p></div><Link to="/family-tree" className="rounded-xl bg-primary px-3 py-2 text-[10px] font-black uppercase tracking-wider text-white">View full tree</Link></header><div className="flex flex-wrap items-center justify-center gap-5 p-8 sm:gap-8">{members.slice(0, 6).map((member) => <Link key={member.id} to={`/profile/${member.id}`} title={`Open ${member.name}'s profile`} className="group flex w-20 flex-col items-center gap-2 text-center"><span className="h-14 w-14 overflow-hidden rounded-full border-2 border-slate-200 p-0.5 transition group-hover:border-primary dark:border-slate-700"><img src={member.avatar} alt="" className="h-full w-full rounded-full object-cover" /></span><span className="w-full truncate text-[10px] font-bold text-slate-700 group-hover:text-primary dark:text-slate-200">{member.name}</span></Link>)}</div><div className="flex items-center justify-center gap-2 border-t border-slate-100 p-4 text-xs text-slate-400 dark:border-slate-800"><GitFork size={14} className="text-primary" /> Explore your connected family stories</div></section>
        <section className="rounded-3xl border border-slate-100 bg-white p-5 shadow-premium dark:border-slate-800 dark:bg-[#111D29]"><header className="mb-5 flex items-center justify-between"><div><h2 className="text-sm font-black text-slate-900 dark:text-white">Family activity</h2><p className="mt-1 text-[10px] text-slate-400">Recent updates from the archive</p></div><Link to="/notifications" aria-label="View notifications" className="rounded-xl bg-primary/10 p-2 text-primary"><Bell size={16} /></Link></header>{recentActivities.length ? <div className="space-y-4">{recentActivities.map((activity) => <article key={activity.id} className="flex min-w-0 gap-3"><img src={activity.avatar} alt="" className="h-9 w-9 shrink-0 rounded-xl object-cover" /><div className="min-w-0 flex-1"><p className="text-xs leading-relaxed text-slate-700 dark:text-slate-200"><strong>{activity.user}</strong> {activity.action}</p><p className="mt-1 truncate text-[10px] font-bold text-primary">{activity.detail}</p></div><time className="shrink-0 text-[9px] text-slate-400">{activity.time}</time></article>)}</div> : <p className="py-8 text-center text-xs text-slate-500">Archive activity will appear here.</p>}<div className="mt-6 rounded-2xl bg-primary p-5 text-white"><Quote size={19} className="opacity-60" /><p className="mt-2 text-sm font-semibold italic">“A family’s story is a gift passed forward.”</p><Link to="/life-story" className="mt-3 inline-flex items-center gap-1 text-[10px] font-black uppercase tracking-wider text-white/80 hover:text-white">Explore life stories <ArrowRight size={12} /></Link></div></section>
      </div>
      <div className="grid gap-4 sm:grid-cols-2"><Link to="/documents" className="flex items-center gap-4 rounded-2xl border border-slate-100 bg-white p-5 transition hover:border-primary/40 dark:border-slate-800 dark:bg-[#111D29]"><span className="rounded-xl bg-primary/10 p-3 text-primary"><FileText size={18} /></span><span><strong className="block text-sm text-slate-900 dark:text-white">Heritage Vault</strong><small className="text-xs text-slate-500">Browse births, deeds, letters, and records.</small></span><ArrowRight size={16} className="ml-auto text-slate-400" /></Link><Link to="/announcements" className="flex items-center gap-4 rounded-2xl border border-slate-100 bg-white p-5 transition hover:border-primary/40 dark:border-slate-800 dark:bg-[#111D29]"><span className="rounded-xl bg-primary/10 p-3 text-primary"><Bell size={18} /></span><span><strong className="block text-sm text-slate-900 dark:text-white">Announcements</strong><small className="text-xs text-slate-500">Official news and family milestones.</small></span><ArrowRight size={16} className="ml-auto text-slate-400" /></Link></div>
    </div>
  );
}
